//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BarManagerModel", "FK_Transactions_PaymentMethod", "Payment_Method", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BarManager.DL.Payment_Method), "Transactions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BarManager.DL.Transaction), true)]
[assembly: EdmRelationshipAttribute("BarManagerModel", "FK_Transactions_TaxRate", "Tax_Rate", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BarManager.DL.Tax_Rate), "Transactions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BarManager.DL.Transaction), true)]
[assembly: EdmRelationshipAttribute("BarManagerModel", "FK_Transactions_TransactionType", "Transaction_Type", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BarManager.DL.Transaction_Type), "Transactions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BarManager.DL.Transaction), true)]
[assembly: EdmRelationshipAttribute("BarManagerModel", "FK_Transactions_Vendor", "Vendor", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BarManager.DL.Vendor), "Transactions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BarManager.DL.Transaction), true)]

#endregion

namespace BarManager.DL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BarManagerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BarManagerEntities object using the connection string found in the 'BarManagerEntities' section of the application configuration file.
        /// </summary>
        public BarManagerEntities() : base("name=BarManagerEntities", "BarManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BarManagerEntities object.
        /// </summary>
        public BarManagerEntities(string connectionString) : base(connectionString, "BarManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BarManagerEntities object.
        /// </summary>
        public BarManagerEntities(EntityConnection connection) : base(connection, "BarManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Payment_Method> Payment_Methods
        {
            get
            {
                if ((_Payment_Methods == null))
                {
                    _Payment_Methods = base.CreateObjectSet<Payment_Method>("Payment_Methods");
                }
                return _Payment_Methods;
            }
        }
        private ObjectSet<Payment_Method> _Payment_Methods;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tax_Rate> Tax_Rates
        {
            get
            {
                if ((_Tax_Rates == null))
                {
                    _Tax_Rates = base.CreateObjectSet<Tax_Rate>("Tax_Rates");
                }
                return _Tax_Rates;
            }
        }
        private ObjectSet<Tax_Rate> _Tax_Rates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Transaction_Type> Transaction_Types
        {
            get
            {
                if ((_Transaction_Types == null))
                {
                    _Transaction_Types = base.CreateObjectSet<Transaction_Type>("Transaction_Types");
                }
                return _Transaction_Types;
            }
        }
        private ObjectSet<Transaction_Type> _Transaction_Types;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Transaction> Transactions
        {
            get
            {
                if ((_Transactions == null))
                {
                    _Transactions = base.CreateObjectSet<Transaction>("Transactions");
                }
                return _Transactions;
            }
        }
        private ObjectSet<Transaction> _Transactions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vendor> Vendors
        {
            get
            {
                if ((_Vendors == null))
                {
                    _Vendors = base.CreateObjectSet<Vendor>("Vendors");
                }
                return _Vendors;
            }
        }
        private ObjectSet<Vendor> _Vendors;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Payment_Methods EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPayment_Methods(Payment_Method payment_Method)
        {
            base.AddObject("Payment_Methods", payment_Method);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tax_Rates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTax_Rates(Tax_Rate tax_Rate)
        {
            base.AddObject("Tax_Rates", tax_Rate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Transaction_Types EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTransaction_Types(Transaction_Type transaction_Type)
        {
            base.AddObject("Transaction_Types", transaction_Type);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Transactions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTransactions(Transaction transaction)
        {
            base.AddObject("Transactions", transaction);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vendors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVendors(Vendor vendor)
        {
            base.AddObject("Vendors", vendor);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BarManagerModel", Name="Payment_Method")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Payment_Method : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Payment_Method object.
        /// </summary>
        /// <param name="payment_Method_ID">Initial value of the Payment_Method_ID property.</param>
        public static Payment_Method CreatePayment_Method(global::System.Int32 payment_Method_ID)
        {
            Payment_Method payment_Method = new Payment_Method();
            payment_Method.Payment_Method_ID = payment_Method_ID;
            return payment_Method;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Payment_Method_ID
        {
            get
            {
                return _Payment_Method_ID;
            }
            set
            {
                if (_Payment_Method_ID != value)
                {
                    OnPayment_Method_IDChanging(value);
                    ReportPropertyChanging("Payment_Method_ID");
                    _Payment_Method_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Payment_Method_ID");
                    OnPayment_Method_IDChanged();
                }
            }
        }
        private global::System.Int32 _Payment_Method_ID;
        partial void OnPayment_Method_IDChanging(global::System.Int32 value);
        partial void OnPayment_Method_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Payment_MethodName
        {
            get
            {
                return _Payment_MethodName;
            }
            set
            {
                OnPayment_MethodNameChanging(value);
                ReportPropertyChanging("Payment_MethodName");
                _Payment_MethodName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Payment_MethodName");
                OnPayment_MethodNameChanged();
            }
        }
        private global::System.String _Payment_MethodName;
        partial void OnPayment_MethodNameChanging(global::System.String value);
        partial void OnPayment_MethodNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BarManagerModel", "FK_Transactions_PaymentMethod", "Transactions")]
        public EntityCollection<Transaction> Transactions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transaction>("BarManagerModel.FK_Transactions_PaymentMethod", "Transactions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transaction>("BarManagerModel.FK_Transactions_PaymentMethod", "Transactions", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BarManagerModel", Name="Tax_Rate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tax_Rate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tax_Rate object.
        /// </summary>
        /// <param name="tax_Rate_ID">Initial value of the Tax_Rate_ID property.</param>
        public static Tax_Rate CreateTax_Rate(global::System.Int32 tax_Rate_ID)
        {
            Tax_Rate tax_Rate = new Tax_Rate();
            tax_Rate.Tax_Rate_ID = tax_Rate_ID;
            return tax_Rate;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tax_Rate_ID
        {
            get
            {
                return _Tax_Rate_ID;
            }
            set
            {
                if (_Tax_Rate_ID != value)
                {
                    OnTax_Rate_IDChanging(value);
                    ReportPropertyChanging("Tax_Rate_ID");
                    _Tax_Rate_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Tax_Rate_ID");
                    OnTax_Rate_IDChanged();
                }
            }
        }
        private global::System.Int32 _Tax_Rate_ID;
        partial void OnTax_Rate_IDChanging(global::System.Int32 value);
        partial void OnTax_Rate_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Tax_RateName
        {
            get
            {
                return _Tax_RateName;
            }
            set
            {
                OnTax_RateNameChanging(value);
                ReportPropertyChanging("Tax_RateName");
                _Tax_RateName = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tax_RateName");
                OnTax_RateNameChanged();
            }
        }
        private Nullable<global::System.Decimal> _Tax_RateName;
        partial void OnTax_RateNameChanging(Nullable<global::System.Decimal> value);
        partial void OnTax_RateNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BarManagerModel", "FK_Transactions_TaxRate", "Transactions")]
        public EntityCollection<Transaction> Transactions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transaction>("BarManagerModel.FK_Transactions_TaxRate", "Transactions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transaction>("BarManagerModel.FK_Transactions_TaxRate", "Transactions", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BarManagerModel", Name="Transaction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Transaction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Transaction object.
        /// </summary>
        /// <param name="transactionID">Initial value of the TransactionID property.</param>
        public static Transaction CreateTransaction(global::System.Int32 transactionID)
        {
            Transaction transaction = new Transaction();
            transaction.TransactionID = transactionID;
            return transaction;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TransactionID
        {
            get
            {
                return _TransactionID;
            }
            set
            {
                if (_TransactionID != value)
                {
                    OnTransactionIDChanging(value);
                    ReportPropertyChanging("TransactionID");
                    _TransactionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TransactionID");
                    OnTransactionIDChanged();
                }
            }
        }
        private global::System.Int32 _TransactionID;
        partial void OnTransactionIDChanging(global::System.Int32 value);
        partial void OnTransactionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _Amount;
        partial void OnAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reason
        {
            get
            {
                return _Reason;
            }
            set
            {
                OnReasonChanging(value);
                ReportPropertyChanging("Reason");
                _Reason = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reason");
                OnReasonChanged();
            }
        }
        private global::System.String _Reason;
        partial void OnReasonChanging(global::System.String value);
        partial void OnReasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Details
        {
            get
            {
                return _Details;
            }
            set
            {
                OnDetailsChanging(value);
                ReportPropertyChanging("Details");
                _Details = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Details");
                OnDetailsChanged();
            }
        }
        private global::System.String _Details;
        partial void OnDetailsChanging(global::System.String value);
        partial void OnDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Image);
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.Byte[] _Image;
        partial void OnImageChanging(global::System.Byte[] value);
        partial void OnImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FK_Tax_Rate
        {
            get
            {
                return _FK_Tax_Rate;
            }
            set
            {
                OnFK_Tax_RateChanging(value);
                ReportPropertyChanging("FK_Tax_Rate");
                _FK_Tax_Rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_Tax_Rate");
                OnFK_Tax_RateChanged();
            }
        }
        private Nullable<global::System.Int32> _FK_Tax_Rate;
        partial void OnFK_Tax_RateChanging(Nullable<global::System.Int32> value);
        partial void OnFK_Tax_RateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FK_Payment_Method
        {
            get
            {
                return _FK_Payment_Method;
            }
            set
            {
                OnFK_Payment_MethodChanging(value);
                ReportPropertyChanging("FK_Payment_Method");
                _FK_Payment_Method = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_Payment_Method");
                OnFK_Payment_MethodChanged();
            }
        }
        private Nullable<global::System.Int32> _FK_Payment_Method;
        partial void OnFK_Payment_MethodChanging(Nullable<global::System.Int32> value);
        partial void OnFK_Payment_MethodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FK_Transaction_Type
        {
            get
            {
                return _FK_Transaction_Type;
            }
            set
            {
                OnFK_Transaction_TypeChanging(value);
                ReportPropertyChanging("FK_Transaction_Type");
                _FK_Transaction_Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_Transaction_Type");
                OnFK_Transaction_TypeChanged();
            }
        }
        private Nullable<global::System.Int32> _FK_Transaction_Type;
        partial void OnFK_Transaction_TypeChanging(Nullable<global::System.Int32> value);
        partial void OnFK_Transaction_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FK_Vendor
        {
            get
            {
                return _FK_Vendor;
            }
            set
            {
                OnFK_VendorChanging(value);
                ReportPropertyChanging("FK_Vendor");
                _FK_Vendor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FK_Vendor");
                OnFK_VendorChanged();
            }
        }
        private Nullable<global::System.Int32> _FK_Vendor;
        partial void OnFK_VendorChanging(Nullable<global::System.Int32> value);
        partial void OnFK_VendorChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BarManagerModel", "FK_Transactions_PaymentMethod", "Payment_Method")]
        public Payment_Method Payment_Method
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Payment_Method>("BarManagerModel.FK_Transactions_PaymentMethod", "Payment_Method").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Payment_Method>("BarManagerModel.FK_Transactions_PaymentMethod", "Payment_Method").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Payment_Method> Payment_MethodReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Payment_Method>("BarManagerModel.FK_Transactions_PaymentMethod", "Payment_Method");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Payment_Method>("BarManagerModel.FK_Transactions_PaymentMethod", "Payment_Method", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BarManagerModel", "FK_Transactions_TaxRate", "Tax_Rate")]
        public Tax_Rate Tax_Rate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tax_Rate>("BarManagerModel.FK_Transactions_TaxRate", "Tax_Rate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tax_Rate>("BarManagerModel.FK_Transactions_TaxRate", "Tax_Rate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tax_Rate> Tax_RateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tax_Rate>("BarManagerModel.FK_Transactions_TaxRate", "Tax_Rate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tax_Rate>("BarManagerModel.FK_Transactions_TaxRate", "Tax_Rate", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BarManagerModel", "FK_Transactions_TransactionType", "Transaction_Type")]
        public Transaction_Type Transaction_Type
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Transaction_Type>("BarManagerModel.FK_Transactions_TransactionType", "Transaction_Type").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Transaction_Type>("BarManagerModel.FK_Transactions_TransactionType", "Transaction_Type").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Transaction_Type> Transaction_TypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Transaction_Type>("BarManagerModel.FK_Transactions_TransactionType", "Transaction_Type");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Transaction_Type>("BarManagerModel.FK_Transactions_TransactionType", "Transaction_Type", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BarManagerModel", "FK_Transactions_Vendor", "Vendor")]
        public Vendor Vendor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vendor>("BarManagerModel.FK_Transactions_Vendor", "Vendor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vendor>("BarManagerModel.FK_Transactions_Vendor", "Vendor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Vendor> VendorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vendor>("BarManagerModel.FK_Transactions_Vendor", "Vendor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Vendor>("BarManagerModel.FK_Transactions_Vendor", "Vendor", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BarManagerModel", Name="Transaction_Type")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Transaction_Type : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Transaction_Type object.
        /// </summary>
        /// <param name="transaction_Type_ID">Initial value of the Transaction_Type_ID property.</param>
        public static Transaction_Type CreateTransaction_Type(global::System.Int32 transaction_Type_ID)
        {
            Transaction_Type transaction_Type = new Transaction_Type();
            transaction_Type.Transaction_Type_ID = transaction_Type_ID;
            return transaction_Type;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Transaction_Type_ID
        {
            get
            {
                return _Transaction_Type_ID;
            }
            set
            {
                if (_Transaction_Type_ID != value)
                {
                    OnTransaction_Type_IDChanging(value);
                    ReportPropertyChanging("Transaction_Type_ID");
                    _Transaction_Type_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Transaction_Type_ID");
                    OnTransaction_Type_IDChanged();
                }
            }
        }
        private global::System.Int32 _Transaction_Type_ID;
        partial void OnTransaction_Type_IDChanging(global::System.Int32 value);
        partial void OnTransaction_Type_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Transaction_TypeName
        {
            get
            {
                return _Transaction_TypeName;
            }
            set
            {
                OnTransaction_TypeNameChanging(value);
                ReportPropertyChanging("Transaction_TypeName");
                _Transaction_TypeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Transaction_TypeName");
                OnTransaction_TypeNameChanged();
            }
        }
        private global::System.String _Transaction_TypeName;
        partial void OnTransaction_TypeNameChanging(global::System.String value);
        partial void OnTransaction_TypeNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BarManagerModel", "FK_Transactions_TransactionType", "Transactions")]
        public EntityCollection<Transaction> Transactions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transaction>("BarManagerModel.FK_Transactions_TransactionType", "Transactions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transaction>("BarManagerModel.FK_Transactions_TransactionType", "Transactions", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BarManagerModel", Name="Vendor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vendor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vendor object.
        /// </summary>
        /// <param name="vendorID">Initial value of the VendorID property.</param>
        public static Vendor CreateVendor(global::System.Int32 vendorID)
        {
            Vendor vendor = new Vendor();
            vendor.VendorID = vendorID;
            return vendor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VendorID
        {
            get
            {
                return _VendorID;
            }
            set
            {
                if (_VendorID != value)
                {
                    OnVendorIDChanging(value);
                    ReportPropertyChanging("VendorID");
                    _VendorID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VendorID");
                    OnVendorIDChanged();
                }
            }
        }
        private global::System.Int32 _VendorID;
        partial void OnVendorIDChanging(global::System.Int32 value);
        partial void OnVendorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VendorName
        {
            get
            {
                return _VendorName;
            }
            set
            {
                OnVendorNameChanging(value);
                ReportPropertyChanging("VendorName");
                _VendorName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VendorName");
                OnVendorNameChanged();
            }
        }
        private global::System.String _VendorName;
        partial void OnVendorNameChanging(global::System.String value);
        partial void OnVendorNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BarManagerModel", "FK_Transactions_Vendor", "Transactions")]
        public EntityCollection<Transaction> Transactions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transaction>("BarManagerModel.FK_Transactions_Vendor", "Transactions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transaction>("BarManagerModel.FK_Transactions_Vendor", "Transactions", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
